version: '3.8'

services:
  cms:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5004:5000
    environment: 
      - FLASK_ENV=development
      - FLASK_APP=FlaskWebProject/__init__.py
      - SQL_SERVER=${SQL_SERVER}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER_NAME=${SQL_USER_NAME}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - BLOB_ACCOUNT=${BLOB_ACCOUNT}
      - BLOB_STORAGE_KEY=${BLOB_STORAGE_KEY}
      - BLOB_CONTAINER=${BLOB_CONTAINER}
      - CLIENT_ID=${APP_REGISTRATION_CLIENT_ID}
      - CLIENT_SECRET=${APP_REGISTRATION_CLIENT_SECRET}
      - URL_SCHEME=${APP_URL_SCHEME}
